#!/bin/bash
# Author: Remigijus Jarmalavičius <remigijus@jarmalavicius.lt>
# Author: Vytautas Povilaitis <php-checker@vytux.lt>

ROOT_DIR="$(pwd)/"
LIST=$(git diff-index --cached --name-status HEAD | grep  -E "^(A|C|M|R)" | awk {'print $2'})
ERRORS_BUFFER=""
for file in $LIST
do
  # PHP syntax check for php files
  EXTENSION=$(echo "$file" | grep -E ".php$|.module$|.inc$|.install$")
  if [ "$EXTENSION" != "" ]; then
    echo "Checking file: $file"
    ERRORS=$(php -l $ROOT_DIR$file 2>&1 | grep "Parse error")
    if [ "$ERRORS" != "" ]; then
      if [ "$ERRORS_BUFFER" != "" ]; then
        ERRORS_BUFFER="$ERRORS_BUFFER\n* $ERRORS"
      else
        ERRORS_BUFFER="$ERRORS"
      fi
      echo "Syntax errors found in file: $file "
    fi
  fi
done

# Print errors
if [ "$ERRORS_BUFFER" != "" ]; then
    echo
    echo "These errors were found in try-to-commit files: "
    echo -e $ERRORS_BUFFER
    echo
    echo "Can't commit, fix errors first."
    exit 1
else
    echo "Commited successfully."
fi
