#!/bin/bash
# Author: Remigijus Jarmalavičius <remigijus@jarmalavicius.lt>
# Author: Vytautas Povilaitis <php-checker@vytux.lt>
# Author: Kornel Lugosi <coornail@gmail.com>

ROOT_DIR="$(pwd)/"
LIST=$(git diff-index --cached --name-status HEAD | grep  -E "^(A|C|M|R)" | awk {'print $2'})
ERRORS_BUFFER=""
for file in $LIST
do
  # Check for conflict markers
  ERRORS=$(grep -E '>>[>*]>>|<<[<*]<<|==[=*]==' $file | grep -v 'Binary')
  if [ "$ERRORS" != "" ]; then
    ERRORS_BUFFER="$ERRORS_BUFFER- Conflict marker found in file $ROOT_DIR$file\n"
    ERRORS=""
  fi

  # PHP syntax check for php files
  EXTENSION=$(echo "$file" | grep -E ".php$|.module$|.inc$|.install$")
  if [ "$EXTENSION" != "" ]; then
    ERRORS=$(php -l $ROOT_DIR$file 2>&1 | grep "Parse error")
    if [ "$ERRORS" != "" ]; then
      ERRORS_BUFFER="$ERRORS_BUFFER- $ERRORS\n"
    fi
  fi
done

# Print errors
if [ "$ERRORS_BUFFER" != "" ]; then
    echo "Errors found in index:"
    echo -e $ERRORS_BUFFER
    exit 1
else
    echo "Commited successfully."
fi
